const MAXX_SELECTORS = {
  title: [
    "h1.product-title",
    "h1.product__title",
    "[data-product-title]",
    ".product-single__title",
    ".lot-title",
    ".listing-title",
    "h1",
  ],
  price: [
    ".product-price",
    ".price__regular .price-item--regular",
    "[data-product-price]",
    ".product__price",
    ".current-price",
    ".lot-price",
    ".price",
  ],
  description: [
    ".product-description",
    ".product__description",
    "[data-product-description]",
    ".lot-description",
    ".listing-description",
    ".notes",
    ".rte",
    "#product-description",
  ],
  images: [
    ".product-gallery img",
    ".product__media img",
    "[data-product-image]",
    ".product-single__photo img",
    ".product-image img",
    ".lot-images img",
    ".listing-images img",
    ".gallery img",
    ".carousel img",
    ".swiper-slide img",
    "#imageGallery img",
    ".main-image img",
    "img.lot-image",
    "img.listing-image",
  ],
  variants: [".product-form select", ".variant-selector select"],
};
