const MAXX_SELECTORS = {
  title: [
    ".lot-title",
    ".listing-title",
    ".item-title",
    "h1.lot-details-title",
    "[class*='LotTitle']",
    "[class*='lot-title']",
    "h1.product-title",
    "h1.product__title",
    "[data-product-title]",
    ".product-single__title",
    "h1",
  ],
  price: [
    ".current-bid",
    ".current-price",
    "[class*='CurrentBid']",
    "[class*='current-bid']",
    ".lot-price",
    ".product-price",
    ".price__regular .price-item--regular",
    "[data-product-price]",
    ".product__price",
    ".price",
  ],
  description: [
    ".lot-description",
    ".listing-description",
    ".item-description",
    ".lot-notes",
    ".notes",
    "[class*='LotDescription']",
    ".product-description",
    ".product__description",
    "[data-product-description]",
    ".rte",
    "#product-description",
  ],
  images: [
    ".lot-images img",
    ".listing-images img",
    ".lot-gallery img",
    "[class*='LotImage'] img",
    "[class*='lot-image']",
    ".gallery img",
    ".carousel img",
    ".swiper-slide img",
    "#imageGallery img",
    ".main-image img",
    "img.lot-image",
    "img.listing-image",
    ".product-gallery img",
    ".product__media img",
    "[data-product-image]",
    ".product-single__photo img",
    ".product-image img",
    "img[data-zoom]",
    "img[srcset]",
  ],
  variants: [".product-form select", ".variant-selector select"],
  condition: [
    ".item-condition",
    ".condition",
    "[class*='condition']",
    "[class*='Condition']",
  ],
  auctionEnd: [
    "[class*='end']",
    "[class*='closes']",
    "[data-end]",
    ".auction-end",
    ".lot-ends",
    "[class*='Countdown']",
    "[class*='TimeLeft']",
  ],
};
